### ISSUE TITLE
some problem with go 1.4.2

### ISSUE THREAD

**Issue by lukaszkaleta** [mpratt/environment-config#1]
cd ctr && go build -ldflags "-X github.com/docker/containerd.GitCommit= " -o ../bin/ctr
go build: when using gccgo toolchain, please pass linker flags using -gccgoflags, not -ldflags
cd containerd && go build -ldflags "-X github.com/docker/containerd.GitCommit= "  -tags "" -o ../bin/containerd
../runtime/process.go:16:2: C source files not allowed when not using cgo: gccgo_c.c
Makefile:49: recipe for target 'daemon' failed
make: *** [daemon] Error 1

**Comment by mpratt** [comment]
Im so sorry @lukaszkaleta ,

Im using slackware 14.2 and go 1.7 and everything seems to be compiling without a problem.
My slackbuilds are for my own personal usage and I dont have much time to debug other systems, so I focus on what Im using right now.

If you can, please update your google-go-lang version!
